#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Cheatsheet
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon ⌨️
# @raycast.packageName Dotfiles
# @raycast.argument1 {"type": "dropdown", "placeholder": "Cheatsheet", "data": [{"title": "All", "value": "all"}, {"title": "Shell aliases", "value": "shell-aliases"}, {"title": "Shell functions", "value": "shell-functions"}, {"title": "Git aliases", "value": "git-aliases"}, {"title": "Karabiner", "value": "karabiner"}, {"title": "Neovim", "value": "neovim"}, {"title": "WezTerm", "value": "wezterm"}, {"title": "Herdr", "value": "herdr"}, {"title": "VS Code", "value": "vs-code"}, {"title": "Lazygit", "value": "lazygit"}, {"title": "Yazi", "value": "yazi"}, {"title": "Claude", "value": "claude"}, {"title": "Raycast", "value": "raycast"}]}
# @raycast.argument2 { "type": "text", "placeholder": "Search (optional)", "optional": true }

# Documentation:
# @raycast.description Show the keybinding cheatsheet for one app, or all of them, optionally filtered by a search. The dropdown is regenerated by scripts/generate-cheatsheet.py.
# @raycast.author Matine Chabrier

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEYS="$HOME/.local/bin/keys"
SHEETS="$DIR/cheatsheets"

SHEET=(--file "$SHEETS/${1:-all}.md")
[ "${1:-all}" = "all" ] && SHEET=()

if [ -z "${2:-}" ]; then
	exec "$KEYS" --all --plain ${SHEET[@]+"${SHEET[@]}"}
fi

exec "$KEYS" --plain ${SHEET[@]+"${SHEET[@]}"} "$2"
